### PR TITLE
Fixes possible Forwarded header spoofing #11

### LINKED ISSUE #11: Spoofing
Hi,

Correct me if I'm  but it looks like if client sends `X-Forwarded-For: 1.2.3.4, 5.6.7.8` in request, which then goes via trusted proxy (or several), and middleware is configured using `proxy(['ip of trusted proxy'])` then the result is that client Ip appears as `1.2.3.4`, however the actual client IP (detected by first proxy) should be the 3rd in the XFF list.

In other words, the middleware should check XFF IP addresses one by one from right to left, and return first one that is not in the trusted proxies list.

### PR DESCRIPTION
**Pull request by martinssipenko**
I did not focus on the code optimization. What I did was create few test cases and made sure they all pass.

Fixes #11

### CODE REVIEW

**Comment by oscarotero** [comment]
Thank you!

**Comment by martinssipenko** [comment]
@oscarotero can you please tag/release this fix?

**Comment by oscarotero** [comment]
I will today 😃

**Comment by oscarotero** [comment]
v1.0.2 released

**Pull request merged**
